### ISSUE TITLE
jsPerf alternative?

### ISSUE THREAD

**Issue by tomByrer** [Kikobeats/javascript-mythbusters#5]
I really do love jsPerf (even wrote a [tutorial for jsPerf](https://github.com/tomByrer/jsperf-tutorial) for a Meetup).  But it needs Java... which is kinda something I try to avoid.

Thanks for your resource; I'll have to add in my finds later.

**Comment by Kikobeats** [comment]
Really I don't know, maybe @mathiasbynens knows alternatives 😝

**Comment by mathiasbynens** [comment]
jsPerf doesn’t need Java…

https://jsperf.com/faq#java-applet

> The applet you’re talking about is just a clever trick we’re using to expose Java’s nanosecond timer to JavaScript, so we can use it to get more accurate test results. jsPerf will still work fine if you disable Java; it might just take a little longer to run tests.

**Comment by Kikobeats** [comment]
badass! 😎
